Changed: fix cn translate
termux/termux.github.io pull request #81
Opened 2022-11-26 02:57 UTC by NekoYyang

Your translation seems to be a machine translation, and I tried it and couldn't read it

2022-11-26 05:40 UTC, 2096779623 requested changes

2022-11-26 05:40 UTC, 2096779623 commented on _data/t/cn/views/home.yml
> +  Termux是一个<strong>适用于 Android 的终端模拟器，其环境类似于 Linux 环境</strong>。
```suggestion
  Termux是一个<strong>适用于 Android 的终端模拟器，其环境类似于 Linux 环境</strong>，
```

2022-11-26 05:40 UTC, 2096779623 commented on _data/t/cn/views/home.yml
> +  Termux 会自动进行最小安装
```suggestion
  Termux 会自动进行安装基本系统
```
missing a noun.

2022-11-26 05:54 UTC, DreamOneX commented on _data/t/cn/views/home.yml
> +      Termux 将标准的软件包与仿真终端结合在一个完美的开源解决方案中。
The translation should not be too rigid, otherwise original texts will translate to strange things. This may be out of habit, semantics, etc. Using Chinese as an example, you can't translate `草` to `Grass`. All that said, I think it's appropriate to use `完美的`(meaning perfect) here.

2022-11-26 05:55 UTC, DreamOneX commented on _data/t/cn/views/home.yml
> +  Termux 会自动进行最小安装
Chinese grammar allows this, it's not a missing ingredient. If you change it like this, you will encounter another problem - called improper matching

2022-11-26 06:00 UTC, DreamOneX commented on _data/t/cn/views/home.yml
> +      你可以在在 bash、fish 或 zsh 和 nano、Emacs 或 Vim 之间进行选择。
Also, `进行选择` is a duplicate, It's better to just keep the `选择`

2022-11-26 06:05 UTC, DreamOneX commented on _data/t/cn/views/home.yml
> +      你可以在在 bash、fish 或 zsh 和 nano、Emacs 或 Vim 之间进行选择。
```suggestion
      你可以在在 bash、fish 或 zsh 和 nano、Emacs 或 Vim 之间选择。
```

Also, `进行选择` is a duplicate, It's better to just keep the `选择`

2022-11-26 06:08 UTC, 2096779623 commented on _data/t/cn/views/home.yml
> +      Termux 将标准的软件包与仿真终端结合在一个完美的开源解决方案中。
```suggestion
      Termux 将标准的软件包与仿真终端结合在一个优秀的开源解决方案中。
```

2022-11-26 11:55 UTC, NekoYyang commented on _data/t/cn/views/home.yml
> +      Termux 将标准的软件包与仿真终端结合在一个完美的开源解决方案中。
If the beautiful one is used, this sentence will make people feel a little bit wrong when reading, so I think the perfect one is better

2022-11-26 12:07 UTC, NekoYyang commented on _data/t/cn/views/home.yml
> +  Termux 会自动进行最小安装
```suggestion
  Termux 会自动进行最小安装
```

2023-01-31 14:24 UTC, 2096779623 commented
Instead of updating upstream like this, use the following command to update upstream by rebasing:
```
git reset --hard e194d19d00acf81b8d6db981ccee6074d297f915
git remote add upstream https://github.com/termux/termux.github.io/
git pull upstream master --rebase
git push origin master -f
```

2023-06-18 06:28 UTC, NekoYyang reviewed
ok

2023-06-18 09:39 UTC, merged